openapi: 3.0.3
info:
  title: go-sixtysix API
  version: 0.1.0
  contact:
    name: Rumen Damyanov
    email: contact@rumenx.com
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: ok
  /games:
    get:
      summary: List registered games
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: string
  /sessions:
    get:
      summary: List sessions
      parameters:
        - in: query
          name: game
          schema:
            type: string
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Session'
    post:
      summary: Create a session
      parameters:
        - in: query
          name: game
          required: true
          schema:
            type: string
        - in: query
          name: seed
          schema:
            type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
  /sessions/{id}:
    get:
      summary: Get a session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
    delete:
      summary: Delete a session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
    post:
      summary: Apply action to a session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: Updated session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
components:
  schemas:
    Session:
      type: object
      properties:
        id:
          type: string
        gameName:
          type: string
        state:
          type: object
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Action:
      type: object
      properties:
        type:
          type: string
          example: play
        actor:
          type: string
        payload:
          type: object
          example:
            card: 311
            suit: 3
        idempotencyKey:
          type: string
